# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2972e6e89c81f415d2ce7d9dec1ce48ffc5ddbd520f2180a02be9f81f5e5f547f9b142ccaa21f2247502680094f762f5b4f357ef408e9d6f75384fc971adf266

test:
  secret_key_base: 371ff7f2944d27d35cf9d57b35cce5be283a52db8dae2315dc43c457506b243bf27ada668a6ebbd0781250bee5e26b0f34ca785b3961b47a59daac6996f1b15c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
